# Generated by Django 4.0.5 on 2022-06-06 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OmniClass23',
            fields=[
                ('idOmc23', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='idOmc23')),
                ('numMat', models.IntegerField()),
                ('Codigo', models.CharField(max_length=18)),
                ('descriEng', models.CharField(blank=True, max_length=120, null=True)),
                ('descriSpa', models.CharField(blank=True, max_length=120, null=True)),
                ('Nivel', models.IntegerField()),
                ('regFinal', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Omniclass23',
            },
        ),
    ]
